# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

"""Tests for the vLLM wheel release verifier."""

from __future__ import annotations

import hashlib
import json
import shutil
from pathlib import Path

import pytest

from tools.jovian_wheel_release.verify_release_assets import verify_release

COMMIT = "1" * 40
TAG = f"vllm-jovian-cu134-beta-{COMMIT}"
WHEEL = "vllm-1-py3-none-any.whl"
ARCHIVE = f"vllm-jovian-cu134-{COMMIT}.tar.zst"


def write_checksums(directory: Path) -> None:
    """Record the exact inventory generated by build_bundle.sh."""
    names = ["manifest.json", "install.sh", "runtime.lock", "requirements-github.txt"]
    (directory / "SHA256SUMS").write_text(
        "".join(
            f"{hashlib.sha256((directory / name).read_bytes()).hexdigest()}  {name}\n"
            for name in names
        )
        + f"{hashlib.sha256((directory / WHEEL).read_bytes()).hexdigest()}"
        f"  wheels/{WHEEL}\n"
    )


def write_release(directory: Path) -> None:
    """Write the smallest complete release accepted by the verifier."""
    wheel = directory / WHEEL
    wheel.write_bytes(b"wheel")
    manifest = {
        "schema": "local-inference-vllm-wheel-release/v2",
        "source": {"commit": COMMIT},
        "release_tag": TAG,
        "packages": [
            {
                "name": "vllm",
                "file": WHEEL,
                "sha256": hashlib.sha256(b"wheel").hexdigest(),
            }
        ],
    }
    (directory / "manifest.json").write_text(json.dumps(manifest))
    for name in ["install.sh", "runtime.lock", "requirements-github.txt"]:
        (directory / name).write_text(f"fixture: {name}\n")
    (directory / ARCHIVE).write_bytes(b"archive fixture")
    (directory / f"{ARCHIVE}.sha256").write_text(
        f"{hashlib.sha256(b'archive fixture').hexdigest()}  {ARCHIVE}\n"
    )
    write_checksums(directory)


def write_promotion(directory: Path) -> None:
    """Bind promotion evidence to one complete source beta."""
    (directory / "stable-promotion.json").write_text(
        json.dumps(
            {
                "schema": "local-inference-vllm-promotion/v1",
                "status": "byte-identical-promotion",
                "source_release": TAG,
                "source_commit": COMMIT,
                "source_manifest_sha256": hashlib.sha256(
                    (directory / "manifest.json").read_bytes()
                ).hexdigest(),
            }
        )
    )


def test_accepts_matching_release(tmp_path: Path) -> None:
    """Matching source identity and wheel bytes satisfy the contract."""
    write_release(tmp_path)
    verify_release(tmp_path, COMMIT, TAG)


def test_rejects_changed_wheel(tmp_path: Path) -> None:
    """A post-publication wheel modification is rejected."""
    write_release(tmp_path)
    (tmp_path / WHEEL).write_bytes(b"changed")
    with pytest.raises(ValueError, match="wheel digest mismatch"):
        verify_release(tmp_path, COMMIT, TAG)


@pytest.mark.parametrize(
    "name",
    [
        WHEEL,
        "manifest.json",
        "install.sh",
        "runtime.lock",
        "requirements-github.txt",
        "SHA256SUMS",
        ARCHIVE,
        f"{ARCHIVE}.sha256",
    ],
)
def test_rejects_missing_release_asset(tmp_path: Path, name: str) -> None:
    """No consumed or republished asset may be absent."""
    write_release(tmp_path)
    (tmp_path / name).unlink()
    with pytest.raises(ValueError):
        verify_release(tmp_path, COMMIT, TAG)


@pytest.mark.parametrize(
    "name",
    [
        "install.sh",
        "runtime.lock",
        "requirements-github.txt",
        ARCHIVE,
    ],
)
def test_rejects_modified_nonwheel_asset(tmp_path: Path, name: str) -> None:
    """Wheel identity alone cannot authorize modified release contents."""
    write_release(tmp_path)
    (tmp_path / name).write_bytes(b"modified")
    with pytest.raises(ValueError, match="mismatch"):
        verify_release(tmp_path, COMMIT, TAG)


@pytest.mark.parametrize("kind", ["extra", "symlink", "empty_packages", "traversal"])
def test_rejects_invalid_inventory(tmp_path: Path, kind: str) -> None:
    """The release is one vLLM package with an exact regular-file inventory."""
    write_release(tmp_path)
    if kind == "extra":
        (tmp_path / "extra.sh").write_text("unexpected")
    elif kind == "symlink":
        (tmp_path / "install.sh").unlink()
        (tmp_path / "install.sh").symlink_to(tmp_path / "runtime.lock")
    else:
        path = tmp_path / "manifest.json"
        manifest = json.loads(path.read_text())
        if kind == "empty_packages":
            manifest["packages"] = []
        else:
            manifest["packages"][0]["file"] = "../outside.whl"
        path.write_text(json.dumps(manifest))
    with pytest.raises(ValueError):
        verify_release(tmp_path, COMMIT, TAG)


@pytest.mark.parametrize("kind", ["missing", "duplicate", "malformed"])
def test_rejects_incomplete_checksum_inventory(tmp_path: Path, kind: str) -> None:
    """A checksum list cannot omit an asset or silently replace an entry."""
    write_release(tmp_path)
    path = tmp_path / "SHA256SUMS"
    lines = path.read_text().splitlines()
    if kind == "missing":
        lines.pop()
    elif kind == "duplicate":
        lines.append(lines[0])
    else:
        lines[0] = "invalid"
    path.write_text("\n".join(lines) + "\n")
    with pytest.raises(ValueError):
        verify_release(tmp_path, COMMIT, TAG)


def test_reference_bytes_and_promotion_pass(tmp_path: Path) -> None:
    """Matching beta bytes and a source-bound promotion satisfy the contract."""
    release = tmp_path / "release"
    release.mkdir()
    write_release(release)
    reference = tmp_path / "reference"
    shutil.copytree(release, reference)
    verify_release(release, COMMIT, TAG, reference_directory=reference)
    write_promotion(release)
    verify_release(release, COMMIT, TAG, promotion=True, reference_directory=reference)
    with pytest.raises(ValueError, match="requires the source beta reference"):
        verify_release(release, COMMIT, TAG, promotion=True)


@pytest.mark.parametrize(
    "field",
    [
        "schema",
        "status",
        "source_release",
        "source_commit",
        "source_manifest_sha256",
        "empty",
    ],
)
def test_rejects_unbound_promotion(tmp_path: Path, field: str) -> None:
    """An empty or unrelated promotion record cannot authorize stable reuse."""
    release = tmp_path / "release"
    release.mkdir()
    write_release(release)
    reference = tmp_path / "reference"
    shutil.copytree(release, reference)
    write_promotion(release)
    path = release / "stable-promotion.json"
    record = json.loads(path.read_text())
    if field == "empty":
        record = {}
    else:
        record[field] = "unrelated"
    path.write_text(json.dumps(record))
    with pytest.raises(ValueError, match="promotion .* mismatch"):
        verify_release(
            release, COMMIT, TAG, promotion=True, reference_directory=reference
        )


def test_reference_rejects_coordinated_replacement(tmp_path: Path) -> None:
    """Self-consistent substituted bytes must not replace the independent build."""
    release = tmp_path / "release"
    release.mkdir()
    write_release(release)
    reference = tmp_path / "reference"
    shutil.copytree(release, reference)
    (release / "install.sh").write_text("substituted installer")
    write_checksums(release)
    verify_release(release, COMMIT, TAG)
    with pytest.raises(ValueError, match="independent reference mismatch"):
        verify_release(release, COMMIT, TAG, reference_directory=reference)
